### ISSUE TITLE
error: Terminating app due to uncaught exception 'Invalid EvernoteSession setup'

### ISSUE THREAD

**Issue by hermanccw** [Evernote/evernote-sdk-ios#12]
Terminating app due to uncaught exception 'Invalid EvernoteSession setup', reason: 'Please add valid CFBundleURLTypes and CFBundleURLSchemes to your app's Info.plist.''

I've read the instruction and here is my info.plist:

<key>CFBundleURLTypes</key>
    <array>
        <dict>
            <key>CFBundleURLSchemes</key>
            <array>
                <string>evernote key</string>
                <string>fbkey</string>
            </array>
        </dict>
    </array>

evernote key and fbkey masked out.

**Comment by sethhitch** [comment]
You should have a single &lt;string&gt; in your info.plist CFBundleURLSchemes array, containing the string "en-" plus your consumer key. If you consumer key is "foobar", then the string should read "&lt;string&gt;en-foobar&lt;/string&gt;".

Note that we just merged in a change to use an embedded view controller instead of handing the authorization page off to Safari. If you update to the latest, you no longer need to modify your info.plist.

**Comment by hermanccw** [comment]
seth,

how do I update if I am using cocoapods?  Seems like they are still at 0.1.0 version and I've try doing 

dependency 'Evernote-SDK-iOS', :git => 'git://github.com/evernote/evernote-sdk-ios.git', :tag => '0.1.2' without any success
